version: '3.9'

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
    volumes:
      - ./%DJANGO_DIR_NAME%:/%DJANGO_DIR_NAME%
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    ports:
      - 8000:8000
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
    entrypoint: ["/scripts/commands.sh"]
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
  pgpadmin:
    image: dpage/pgadmin4
    env_file:
      - ./dotenv_files/.env
    ports:
      - "16543:80"
    depends_on:
      - psql
  
